### ISSUE TITLE
"numerical instability" error

### ISSUE THREAD

**Issue by khieta** [iic-jku/ddsim#15]
Hi, I was trying to run some files through ddsim_simple and I came across a strange error. On two systems I tried (macOS Big Sur and Linux Ubuntu 20.04), running `build/ddsim_simple --simulate_file <file> --ps --shots 1000` on [this file](https://github.com/iic-jku/ddsim/files/6246386/test.qasm.zip) produces the following error:
```
WARNING in MAll: numerical instability occurred during simulation: |alpha|^2 + |beta|^2 - 1 = -15, but should be 1!
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Added probabilities differ from 1 by 1.000000
Abort trap: 6
```
What's strange is that if I delete the last line in this file (swap q[1], q[15];) then there is no error. 

One potential problem is that I'm using swap and c3x gates, which I didn't see in your example circuits... but simulation seems to work if I delete that last swap gate, so that doesn't seem like the problem. Any thoughts?

**Comment by hillmich** [comment]
Hi, thanks for reaching out.

In the code you linked, there is a declaration of a qubit register `qreg q[14];` with only 14 qubits (indices 0 to 13, inclusive), so the `swap q[1], q[15];` fails as `q[15]` does not exist. Chaning the declaration to `qreg q[16];` makes the code work as far as I can tell.
(Next time we touch the OpenQASM parser we'll add an actually helpful error message.)

I'll close the issue but please do not hesitate to re-open if this does not fix it for you.

**Comment by khieta** [comment]
How embarrassing! Thanks for the help :)
